### ISSUE TITLE
Bisherige Lösung

### ISSUE THREAD

**Issue by BeastyBlacksmith** [Ebrantil/aud#2]
In dem Algorithmus aus der Vorlesung die Matrix sowohl vertikal als auch horizontal halbiert, so dass man teilt bis nur noch Skalare übrig bleiben. Für eine Matrix würde das ungefähr so aussehen:
```
def divide( matrix ):
    print("Divide matrix in 4 smaller matrices")
    printMatrix(matrix)
    rowDiv = round(len( matrix ) / 2)
    colDiv = round(len( matrix[0]) / 2)
    sub1 = [ m[:colDiv] for m in matrix[:rowDiv] ]
    print("\nFirst matrix:")
    printMatrix(sub1)
    sub2 = [ m[colDiv:] for m in matrix[:rowDiv] ]
    print("\nSecond matrix:")
    printMatrix(sub2)
    sub3 = [ m[:colDiv] for m in matrix[rowDiv:] ]
    print("\nThird matrix:")
    printMatrix(sub3)
    sub4 = [ m[colDiv:] for m in matrix[rowDiv:] ]
    print("\nFourth matrix:")
    printMatrix(sub4)
    return [[sub1, sub2], [sub3, sub4]]
```
Vielleicht lässt sich das noch einbauen?

**Comment by laraost** [comment]
Letztendlich ist ja die Frage, was man als elementares Problem ansieht: In der bisherigen Lösung ist es das Produkt einer Zeile und Spalte; bei der Teilung in 4 Matrizen ist es die Multiplikation zweier Skalare. Beides führt zu akzeptablen Teile-und-Herrsche-Algorithmen.

Die einfache Teilung scheint mir weniger kompliziert zu sein. Gerade die Fallunterscheidung, ob die Matrizen noch horizontal/vertikal teilbar sind, ist dann einfacher.
